version: '3.8'

services:
  postgres:
    image: postgres:18.1-alpine3.22
    environment:
      - POSTGRES_DB=billing_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - billing-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d billing_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-service:
    build: ./payment-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/billing_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${PAYMENT_SERVICE_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - billing-network
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  executor:
    build: ./executor
    environment:
      - PAYMENT_SERVICE_URL=http://payment-service:8080/api/v1
    depends_on:
      payment-service:
        condition: service_healthy
    networks:
      - billing-network

networks:
  billing-network:
    driver: bridge