spring:
  application:
    name: payment-service

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.xml

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{rid}] %-5level %logger{36} - %msg%n"

management:
  tracing:
    sampling:
      probability: 1.0